apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe-deployment
  labels:
    app: tic-tac-toe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tic-tac-toe
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
        - name: tic-tac-toe
          image: ghcr.io/hardik783-hub/devsecops-demo:sha-47c198030f20d50f2a922642eb5bdbd435aa4674
          # image will be always automatically updated by  CI/CD pipeline to latest version
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.2"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
      imagePullSecrets:
        - name: github-container-registry       
